FROM python:3.8

WORKDIR /code

COPY . /code/

RUN apt-get update && apt-get install -y --no-install-recommends \
        libpq-dev \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

